books/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.user_index, name='user-index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'add-book/$', views.add_book, name="add-book"),
    url(r'add-known-words/$', views.add_known_words, name="add-known-words"),
    url(r'(?P<book_id>[0-9]+)/book-details/$', views.book_details, name="book-details"),
]

newWords/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'books/', include('books.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.files.storage import FileSystemStorage
from newWords import settings
fileStorage = FileSystemStorage(location=settings.MEDIA_ROOT)
# Create your models here.


class Book(models.Model):
    book_title = models.CharField(max_length=250)
    book_author = models.CharField(max_length=250)
    book_file = models.FileField(storage=fileStorage, blank=True, null=True)
    book_cover = models.FileField(storage=fileStorage, blank=True, null=True)
    book_content = models.TextField(blank=True, null=True)
    all_words = models.TextField(blank=True, null=True)
    known_words = models.TextField(blank=True, null=True)
    unknown_words = models.TextField(blank=True, null=True)
    sugested_words = models.TextField(blank=True, null=True)
    outside_words = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.book_title


class MyUser(AbstractUser):
    books = models.ManyToManyField(Book, blank=True, null=True)
    known_words_file = models.FileField(storage=fileStorage, blank=True, null=True)
    known_words = models.TextField(blank=True, null=True)
    meaning_dict = dict()


books/forms.py
# -*- coding: utf-8 -*-
from django import forms
from books.models import MyUser


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = MyUser
        fields = ['username', 'password']





books/views.py
from django.contrib.auth import authenticate, login
from .forms import RegisterForm
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import Book, MyUser
from django.core.files.storage import FileSystemStorage
from pprint import pprint
import requests
import json
from .text import *


class UserFormView(View):
    form_class = RegisterForm
    template_name = 'books/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('books:user-index')

        return render(request, self.template_name, {'form': form})


def user_index(request):
    curr_user = request.user

    if curr_user.is_active:
        print(curr_user.books.all())
        return render(request, 'books/user_index.html', {'all_books': curr_user.books.all, "curr_user": True})
    else:
        return redirect('books:login')

def add_book(request):
    curr_user = request.user

    if curr_user.is_active:
        if request.method == "POST":
            book_title = request.POST.get('book_title', '')
            book_author = request.POST.get('book_author', '')

            try:
                book_cover = request.FILES['book_cover']
            except():
                book_cover = False

            try:
                book_file_ = request.FILES['book_file']
                fs = FileSystemStorage()
                book_file = fs.save(book_file_.name, book_file_)
            except():
                book_file = False

            if not book_title:
                return render(request, 'books/book_form.html', {"not_completed": "not_completed"})

            book_1 = curr_user.books.create(book_title=book_title, book_author=book_author, book_cover=book_cover,
                                            book_file=book_file)
            book_1.save()
            curr_user.save()
            book_content = book_1.book_file.read()
            book_1.book_content = book_content

            words_list, known_words, unknown_words, outside_words = extract_words(request, book_content)

            end = int(len(words_list.split(',')) / 5)
            sugested_words_ = words_list.split()
            sugested_words = []
            for word in sugested_words_:
                if word in unknown_words.split():
                    sugested_words.append(word)

            sugested_words_str = ''
            for word in sugested_words[:end]:
                sugested_words_str += word + ' '

            book_1.all_words = words_list
            book_1.known_words = known_words
            book_1.unknown_words = unknown_words
            book_1.sugested_words = sugested_words_str
            book_1.outside_words = outside_words
            book_1.save()
            return render(request, 'books/user_index.html', {'all_books': curr_user.books.all, "curr_user": True})

        else:
            if request.user.is_active:
                return render(request, 'books/book_form.html')
            else:
                return redirect('books:login')

    if curr_user.is_active:
        return render(request, 'books/user_index.html', {'all_books': curr_user.books.all()})
    return redirect('books:login')


def add_known_words(request):
    curr_user = request.user

    if curr_user.is_active:
        if request.method == "POST":

            try:
                book_file_ = request.FILES['book_file']
                fs = FileSystemStorage()
                book_file = fs.save(book_file_.name, book_file_)
            except():
                book_file = False

            curr_user.known_words_file = book_file
            curr_user.save()
            book_content = curr_user.known_words_file.read()

            known_words = extract_known_words(book_content)
            # curr_user.known_words = known_words
            # curr_user.save()

            for book in curr_user.books.all():
                curr_known_words = str(book.known_words).split()
                curr_unknown_words = str(book.unknown_words).split()
                curr_sugested_words = str(book.sugested_words).split()
                new_known_words = known_words.split()
                a = len(curr_known_words)
                for word in new_known_words:
                    if word not in curr_known_words:
                        curr_known_words.append(word)
                    if word in curr_unknown_words:
                        curr_unknown_words.remove(word)
                    if word in curr_sugested_words:
                        curr_sugested_words.remove(word)

                known_words = ''
                unknown_words = ''
                sugested_words = ''
                for word in curr_known_words:
                    known_words += word + ' '
                book.known_words = known_words

                for word in curr_unknown_words:
                    unknown_words += word + ' '
                book.unknown_words = unknown_words

                for word in curr_sugested_words:
                    sugested_words += word + ' '
                book.sugested_words = sugested_words

                book.save()
                curr_user.known_words = known_words
                curr_user.save()
            curr_user.save()

            return render(request, 'books/user_index.html', {'all_books': curr_user.books.all, "curr_user": True})

        else:
            if request.user.is_active:
                return render(request, 'books/add_known_words.html')
            else:
                return redirect('books:login')

    if curr_user.is_active:
        return render(request, 'books/user_index.html', {'all_books': curr_user.books.all()})
    return redirect('books:login')


def word_meaning(request, word):
    curr_user = request.user
    try:
        meaning_of_word = curr_user.meaning_dict[word]
        return meaning_of_word
    except:
        pass
    app_id = '17160844'
    app_key = '55f44d4c774f7e52ebffd1b8be3e73e9'
    language = 'en'
    #word = 'Ace'
    url = 'https://od-api.oxforddictionaries.com:443/api/v1/entries/' + language + '/' + word.lower() + '/' + 'definitions'
    try:
        r = requests.get(url, headers={'app_id': app_id, 'app_key': app_key})
        meaning_of_word = json.dumps(r.json()['results'][0]["lexicalEntries"][0]["entries"][0]["senses"][0]["definitions"][0])
        curr_user.meaning_dict[word] = meaning_of_word
    except:
        meaning_of_word = "UNKNOWN WORD"
    return meaning_of_word


#def word_list_meaning(a_word_list):
#    word_dict = dict()
#    request = "hey"
#    for word in a_word_list:
#        word_dict[word] = word_meaning(request,word)
#    return word_dict


def book_details(request, book_id):
    curr_user = request.user
    curr_book = Book.objects.get(pk=book_id)
    book_content = curr_book.book_file.read().decode('utf-8')
    known_words = str(curr_book.known_words).split()
    unknown_words = str(curr_book.unknown_words).split()
    sugested_words = str(curr_book.sugested_words).split()
    red_color = "red"
    black_color = "black"
    book_content = [(word, word_meaning(request, word), red_color) if word in unknown_words else(word, "", black_color) for
                    word in book_content.split()]
    a_dict = {"DIPLOBLASTIC": "Characterizing the ovum when it has two primary germinallayers.",
              "DEFIGURE": "To delineate. [Obs.]These two stones as they are here defigured. Weever.",
              "LOMBARD": "Of or pertaining to Lombardy, or the inhabitants of Lombardy.",
              "BAHAISM": "The religious tenets or practices of the Bahais.",
              "FUMERELL": "See Femerell.",
              "ROYALET": "A petty or powerless king. [R.]there were at this time two other royalets, as only kings by hisleave. Fuller.",
              "TROPHIED": "Adorned with trophies.The trophied arches, storied halls, invade. Pope.",
              "ZEQUIN": "See Sequin.",
              "MILLWRIGHT": "A mechanic whose occupation is to build mills, or to set uptheir machinery.",
              "PHOTOGRAPHOMETER": "An instrument for determining the senluminous rays.",
              "SCHEELIUM": "The metal tungsten. [Obs.]",
              "ALVEOLATE": "Deeply pitted, like a honeycomb.",
              "LIMULUS": "The only existing geno Molucca crab, king crab,horseshoe crab, and horsefoot.",
              "OSMUND": "A fern of the genus O (Osmuronds, ofteas been used in stiffening linen.",
              "POTTEEN": "See Poteen.",
              "UNDERRUN": "To run or pass undein, or of examiningit.",
              "EMPLASTIC1": "Fit to be applied as a plaster; glutinous; adhesive; as,emplastic applications.",
              "RHYTHMICS1": "The department of musical science which treats of the length ofsounds.",
              "PLEU11ROPTERA": "A group of Isectivora, including the colugo.",
              "UNBLO1OD1Y": "Not bloody. Dryden. Unbloody sacrifice. (a) A she Mass.",
              "CINCIN1N1US": "A form of monochasium in which the lateral branche false axis; -- called alsoscoal (#), a.",

books/templates/books/add_known_words.html
{% extends 'books/base.html' %}
{% block title %}Add a New Book{% endblock %}
{% block album_active %}active{% endblock %}
{% block body %}
        {% block logo %}"../../../media/logo.png"{% endblock %}

    <div class="container-fluid" style="padding-top: 100px">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>Add Book</h2><br>
                        {% if not_completed %}
                            <div class="alert alert-danger">
                                <strong>You are required to complete all the fields</strong>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" action="{% url 'books:add-known-words'%}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="email">Upload book file:</label>
                              <div class="col-sm-10">
                                <input type="file" class="form-control" name="book_file">
                              </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>
                              </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

books/templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <title>{% block title %}{% endblock %}</title>
    <!--css-->
    <link rel="stylesheet" href="{% static 'books/css/bootstrap.css' %}" type="text/css" media="all"/>
    <link rel="stylesheet" href="{% static 'books/css/mystyle.css' %}" type="text/css" media="all"/>
    <!--css-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <<script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);
    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link rel="stylesheet" href="{% static 'books/css/flexslider.css' %}" type="text/css" media="screen"/>
    <!--js-->
    <script src="{% static 'books/js/jquery.min.js' %}"></script>
    <script src="{% static 'books/js/bootstrap.min.js' %}"></script>
    <!--js-->
{#    <!--webfonts-->#}
{#    <link href='//fonts.googleapis.com/css?family=Nova+Round' rel='stylesheet' type='text/css'>#}
{#    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic'#}
{#          rel='stylesheet' type='text/css'>#}
{#    <!--webfonts-->#}
    <script src="{% static 'books/js/responsiveslides.min.js' %}"></script>
    <script>
        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                nav: true,
                speed: 500,
                namespace: "callbacks",
                pager: true,
            });
        });
    </script>
    <!--Include jQuery & Filterizr-->
    <script src="{% static 'books/js/jquery.filterizr.js' %}"></script>
    <script src="{% static 'books/js/controls.js' %}"></script>
    <!--Kick off Filterizr-->
    <script type="text/javascript">
        $(function () {
            //Initialize filterizr with default options
            $('.filtr-container').filterizr();
        });
    </script>
    <!--gallery-->
    <!--startsmothscrolling-->
    <script type="text/javascript" src="{% static 'books/js/move-top.js' %}"></script>
    <script type="text/javascript" src="{% static 'books/js/easing.js' %}"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1200);
            });
        });
    </script>
    <script src="{% static 'books/js/jquery.swipebox.min.js' %}"></script>
    <script type="text/javascript">
        jQuery(function ($) {
            $(".swipebox").swipebox();
        });
    </script>
    <!--swipe box js-->
    <style>


    </style>
</head>
<body {% block background_image %}{% endblock %}>
<!--header-->

<nav class="navbar navbar-default"
     style="padding: 0px 0px; position: fixed; top: 0; width:100%; overflow: hidden;z-index: 9999;">
    <div class="container-fluid">
        <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'books:user-index' %}"><i><img src={% block logo %}{% endblock %} style="width: 150px; margin: -15px 0px 0px 0px"></i></a>
            </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <!--
                <li>
                    <a href="#songs">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp Songs
                    </a>
                </li>-->
                <li>
                    <input style='width: 400px; height: 40px; border-radius: 10px; align: center; margin: 10px 0px;'
                           type="text" id="myInput" onkeyup="myFunction()"
                           placeholder="Search for books, articles, authors..">

                </li>
            </ul>


            <ul class="nav navbar-nav navbar-right">

                {% block song_add %}
                {% endblock %}
                {% if user.is_authenticated %}
                    <li class="">
                        <a href="{% url 'books:add-book' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp Add Book
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'books:add-known-words' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp Add Known Words
                        </a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="">
                        <a href="{% url 'books:user-index' %}">
                            <span aria-hidden="true"></span>&nbsp <i>{{ user.username }}</i>
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'books:logout' %}?next={% url 'books:user-index' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp Logout
                        </a>
                    </li>
                {% else %}
                    <li class="">
                        <a href="{% url 'books:login' %}">
                            <span class="glyphicon glyphicon-register" aria-hidden="true"></span>&nbsp Login
                        </a>
                    </li>
                {% endif %}
                <li class="">
                    <a href="{% url 'books:register' %}">
                        <span class="glyphicon glyphicon-register" aria-hidden="true"></span>&nbsp Register
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div>
    <table class='search-table' id="myTable" style="margin: 0px 185px; width: 570px; display: none; background: white;">

    </table>
</div>

<div onmouseover='document.getElementById("myTable").style.display = "none"'>
    {% block body %}
    {% endblock %}
</div>

<script>
/*
    function myFunction() {
        var input, filter, table, tr, td, i, num;
        document.getElementById('myTable').style.display = "inline";
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");

        while (table.rows.length > 0) {
            table.deleteRow(0);
        }
        num = 0;
        "{% for album in albums %}"
            if ("{{ album.album_title }}".toUpperCase().search(filter) !== -1) {
                var row = table.insertRow(num);
                var cell1 = row.insertCell(0);
                var cell2 = row.insertCell(1);
                cell1.innerHTML = "<a href='{% url "books:song-set" album.id %}' style='cursor: pointer; text-decoration: none;'><p>{{ album.album_title }}</p></a>";
                cell2.innerHTML = "<small>Album</small>";
                cell1.style.width = '580px';
                if (num > 5) {
                    return;
                }
                num++;

            }
            "{% endfor %}"
        "{% for album in albums %}"
            "{% for song in album.song_set.all %}"
                if ("{{ song.song_title }}".toUpperCase().search(filter) !== -1) {
                    var row = table.insertRow(num);
                    var cell1 = row.insertCell(0);
                    var cell2 = row.insertCell(1);
                    cell1.innerHTML = "<a href='{% url "books:albums-play-song" album.id song.id %}' style='cursor: pointer; text-decoration: none;'><p>{{ song.song_title }}</p></a>";
                    cell2.innerHTML = "<small>Song</small>";
                    cell1.style.width = '580px';

                    if (num > 5) {
                        return;
                    }
                    num++;
                }
                "{% endfor %}"
            "{% endfor %}"
    }

*/
</script>
</body>
</html>

books/templates/books/book_details.html
{% extends 'books/base.html' %}
{% load static %}
{% block title %}
    {{ request.user.username }}'s Bookshelf
{% endblock %}

{% block body %}
    {% block logo %}"../../../media/logo.png"{% endblock %}
    <div class="col-lg-9" style="margin-top: 2%">
        <div class="page-header">
            <h1>{{ book.book_title | capfirst}}</h1>
        </div>
        <p style="overflow: auto; height: 400px">{% for word, meaning, color in book_content %}<span title="{{ meaning }}"
                                                               style="color: {{ color }}">{{ word }} </span>{% endfor %}
        </p>
    </div>
    <div class="col-lg-3 bs-component" style="margin-top: 5.6%">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#known" data-toggle="tab" aria-expanded="true">Known</a></li>
            <li class=""><a href="#unknown" data-toggle="tab" aria-expanded="false">Unknown</a></li>
            <li class=""><a href="#suggestion" data-toggle="tab" aria-expanded="false">Suggested</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="known">
                <input style='height: 40px; border-radius: 10px; margin: 5px 0px;'
                           type="text" id="myInput" onkeyup="console.log(this.value)"
                           placeholder="Search for a known word">
                <div id="words" style="height: 400px">
                    <ul class="cloud">
                        {% for word in known_words %}
                            <li><a title="#" >{{ word | lower }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="tab-pane fade" id="unknown">
                <input style='height: 40px; border-radius: 10px; margin: 5px 0px;'
                           type="text" id="myInput" onkeyup="console.log(this.value)"
                           placeholder="Search for an unknown word">
                <div id="words" style="height: 400px">
                    <ul class="cloud">
                        {% for word in unknown_words %}
                            <li><a title="" href="#Emien{{ word }}">{{ word | lower }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="tab-pane fade" id="suggestion">
                <div id="words" style="height: 420px">
                    <ul class="cloud">
                        {% for word in sugested_words %}
                            <li><a title="#"
                                   href="javascript:alert('Hello World!');">{{ word | lower }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

books/templates/books/book_form.html
r{% extends 'books/base.html' %}
{% block title %}Add a New Book{% endblock %}
{% block album_active %}active{% endblock %}
{% block body %}
            {% block logo %}"../../../media/logo.png"{% endblock %}

    <div class="container-fluid" style="padding-top: 100px">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>Add Book</h2><br>
                        {% if not_completed %}
                            <div class="alert alert-danger">
                                <strong>You are required to complete all the fields</strong>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" action="{% url 'books:add-book'%}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="email">Book title:</label>
                              <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Enter a title" name="book_title">
                              </div>
                            </div>
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="email">Book Author</label>
                              <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="Enter an author" name="book_author">
                              </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="email">Book Cover:</label>
                                <div class="col-sm-10">
                                    <input type="file" class="form-control" value="more hej" name="book_cover">
                                </div>
                            </div>
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="email">Upload book file:</label>
                              <div class="col-sm-10">
                                <input type="file" class="form-control" name="book_file">
                              </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>
                              </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

books/templates/books/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-3">{{ field.label_tag }}</label>
        <div class="col-sm-9">{{ field }}</div>
    </div>
{% endfor %}

books/templates/books/user_index.html
{% extends 'books/base.html' %}
{% load static %}
{% block body %}
    {% block logo %}"../media/logo.png"{% endblock %}
    <div class="page-header">
        <h1 style="padding: 20px 0px 0px 20px">{{ request.user.username }}'s Bookshelf</h1>
    </div>
    <ul style="padding-top: 50px; margin-left: 51px">
        {% for book in all_books %}
            <li style="display:inline-block">
                <div class="gallery"
                     style="background: url('../../../media/book.png');background-size: 200px;
                     background-repeat: no-repeat; height:350px; width: 270px; text-align: center; border-radius: 10px;">
                    <a href="{% url 'books:book-details' book.id %}">
                        <h1 style="align-content: center; font-size: 40px; width: 73%; color: #e2c50f">{{ book.book_title }}</h1>
{#                        <img src="{{ book.book_cover.url }}" style="width: 245px;height: 250px;">#}

                    </a>
                    <div class="desc" style="overflow:hidden; text-overflow: ellipsis;"><p style="white-space: nowrap;
                    text-overflow: ellipsis; text-align: center; width: 73%; color: white">{{ book.book_author }}</p></div>

                    <a href="#" type="submit" class="glyphicon glyphicon-edit btn btn-info"
                       style="margin: 30% 0% 0% -25%"> Update</a>
                    <form action="#" method="post" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="book_id" value="{{ book_id }}" />
                        <a href="#" type="submit" class="glyphicon glyphicon-trash btn btn-primary"
                           style="margin: 30% 0% 0% 0%"> Delete</a>
                    </form>
                </div>

            </li>
        {% endfor %}
    </ul>

{% endblock %}